---
# tasks file for zabbix_agent_for_linux
- block: # RedHat
  - block: # Версии CentOS
    - name: Установка репозитория для CentOS 7
      command: "rpm -Uvh --force https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"
      when: ansible_distribution_major_version == "7"
    
    - name: Установка репозитория для CentOS 8
      command: "rpm -Uvh --force https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm"
      when: ansible_distribution_major_version == "8"
      
    - name: Установка репозитория для CentOS 9
      command: "rpm -Uvh --force https://repo.zabbix.com/zabbix/5.0/rhel/9/x86_64/zabbix-release-5.0-3.el9.noarch.rpm"
      when: ansible_distribution_major_version == "9"
      
      notify:
        - update cache yum
    
  - name: Установка Zabbix агента
    yum:
      name: zabbix-agent
      state: present
      update_cache: true

  when: ansible_os_family == "RedHat"
  
- block: # Ubuntu
  - block: # Версии Ubuntu
    - name: Установка репозитория для Ubuntu 18.04
      command: "wget --force https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb && dpkg -i zabbix-release_5.0-1+bionic_all.deb"
      when: ansible_distribution_major_version == "18.04"
      
    - name: Установка репозитория для Ubuntu 20.04
      command: "wget --force https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb && dpkg -i zabbix-release_5.0-1+focal_all.deb"
      when: ansible_distribution_major_version == "20.04"
      
    - name: Установка репозитория для Ubuntu 22.04
      command: "wget --force https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-2+ubuntu22.04_all.deb && dpkg -i zabbix-release_5.0-2+ubuntu22.04_all.deb"
      when: ansible_distribution_major_version == "22.04"
      
      notify:
        - update cache apt
    
  - name: Установка Zabbix агента
    apt:
      name: zabbix-agent
      state: present
      update_cache: yes
  
  when: ansible_os_family == "Ubuntu"


- name: Edit conf file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - Restart Zabbix-agent